name: Run Tests and Build

on: push

jobs:
  run-tests-and-build:
    name: Run Tests and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3.3.0

      - name: Use Node 18.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "18"

      - name: Setup pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.1

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Run tsc lint
        run: pnpm lint

      - name: Build
        run: pnpm build
